spring:
  application:
    name: associations-db-consumer
  datasource:
    url: jdbc:h2:file:${NFE_101_HOME}/data/Ecole
    username: sa
    password: password
    driverClassName: org.h2.Driver
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      id.db_structure_naming_strategy: legacy
  sql:
    init:
      mode: always
  h2:
    console.enabled: true      

#http://localhost:8080/h2-console     


Ecole:
  raw-kafka-topic:Ecol.raw
  kafka-server: localhost:9092
